import JSZip from 'jszip';
import html2canvas from 'html2canvas';
import pptxgen from 'pptxgenjs';
import { supabase } from '../lib/supabase';

export const exportAsHTML = (code: string) => {
  const blob = new Blob([code], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "kreo-manifestation.html";
  document.body.appendChild(a); // Required for some browsers
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const exportAsMD = (code: string) => {
  const mdContent = "```html\n" + code.replace(/```(jsx|tsx|javascript|js|html|react|css)?/g, "").replace(/```/g, "").trim() + "\n```";
  const blob = new Blob([mdContent], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "kreo-manifestation.md";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const exportAsZip = async (code: string) => {
  const zip = new JSZip();
  zip.file("index.html", code);
  zip.file("README.md", `# KREO Manifestation\n\nThis artifact was generated by KREO.\n\n## Setup\nSimply open \`index.html\` in any modern browser to view the manifest.`);
  
  const content = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(content);
  const a = document.createElement("a");
  a.href = url;
  a.download = "kreo-dev-package.zip";
  a.click();
  URL.revokeObjectURL(url);
};

export const exportAsPPTX = async (iframeId: string) => {
  const iframe = document.getElementById(iframeId) as HTMLIFrameElement;
  if (!iframe) return;

  const canvas = await html2canvas(iframe.contentDocument!.body);
  const imgData = canvas.toDataURL('image/png');

  const pptx = new pptxgen();
  const slide = pptx.addSlide();
  slide.addImage({ data: imgData, x: 0, y: 0, w: '100%', h: '100%' });
  
  pptx.writeFile({ fileName: "kreo-presentation.pptx" });
};

export const exportToCanva = (code: string) => {
  navigator.clipboard.writeText(code).then(() => {
    window.open('https://www.canva.com/create/', '_blank');
  });
};

export const automatedExportToCanva = async (iframeId: string) => {
  const sourceIframe = document.getElementById(iframeId) as HTMLIFrameElement;
  if (!sourceIframe) {
    window.open('https://www.canva.com/create/', '_blank');
    return;
  }

  try {
    const htmlContent = sourceIframe.srcdoc || sourceIframe.contentDocument?.documentElement.outerHTML || '';
    if (!htmlContent) throw new Error("No content to capture");

    // Blob URL strategy to force same-origin for html2canvas
    const blob = new Blob([htmlContent], { type: "text/html" });
    const url = URL.createObjectURL(blob);

    const hiddenIframe = document.createElement('iframe');
    hiddenIframe.style.position = 'absolute';
    hiddenIframe.style.top = '-9999px';
    hiddenIframe.style.width = '1440px';
    hiddenIframe.style.height = '900px';
    hiddenIframe.style.border = 'none';

    await new Promise<void>((resolve, reject) => {
      hiddenIframe.onload = () => setTimeout(resolve, 500); // Allow fonts to load
      hiddenIframe.onerror = reject;
      hiddenIframe.src = url;
      document.body.appendChild(hiddenIframe);
    });

    const canvas = await html2canvas(hiddenIframe.contentDocument!.body, {
      useCORS: true,
      scale: 2,
      logging: false,
    });
    
    // Clean up
    document.body.removeChild(hiddenIframe);
    URL.revokeObjectURL(url);

    const imageBlob = await new Promise<Blob | null>(res => canvas.toBlob(res, 'image/png'));
    if (!imageBlob) throw new Error("Capture failed");

    const fileName = `canva_${Date.now()}_${Math.random().toString(36).substring(7)}.png`;
    const { error: uploadError } = await supabase.storage
      .from('manifests')
      .upload(fileName, imageBlob);

    if (uploadError) throw uploadError;

    const { data: { publicUrl } } = supabase.storage
      .from('manifests')
      .getPublicUrl(fileName);

    window.open(`https://www.canva.com/design/play?import=${encodeURIComponent(publicUrl)}`, '_blank');
  } catch (err) {
    console.error("[KREO] Canva automation failed:", err);
    window.open('https://www.canva.com/create/', '_blank');
  }
};
