import JSZip from 'jszip';
import html2canvas from 'html2canvas';
import pptxgen from 'pptxgenjs';
import { supabase } from '../lib/supabase';

export const exportAsHTML = (code: string) => {
  const blob = new Blob([code], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "kreo-manifestation.html";
  document.body.appendChild(a); // Required for some browsers
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const exportAsZip = async (code: string) => {
  const zip = new JSZip();
  zip.file("index.html", code);
  zip.file("README.md", `# KREO Manifestation\n\nThis artifact was generated by KREO.\n\n## Setup\nSimply open \`index.html\` in any modern browser to view the manifest.`);
  
  const content = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(content);
  const a = document.createElement("a");
  a.href = url;
  a.download = "kreo-dev-package.zip";
  a.click();
  URL.revokeObjectURL(url);
};

export const exportAsPPTX = async (iframeId: string) => {
  const iframe = document.getElementById(iframeId) as HTMLIFrameElement;
  if (!iframe) return;

  const canvas = await html2canvas(iframe.contentDocument!.body);
  const imgData = canvas.toDataURL('image/png');

  const pptx = new pptxgen();
  const slide = pptx.addSlide();
  slide.addImage({ data: imgData, x: 0, y: 0, w: '100%', h: '100%' });
  
  pptx.writeFile({ fileName: "kreo-presentation.pptx" });
};

export const exportToCanva = (code: string) => {
  navigator.clipboard.writeText(code).then(() => {
    window.open('https://www.canva.com/create/', '_blank');
  });
};

export const automatedExportToCanva = async (iframeId: string) => {
  const iframe = document.getElementById(iframeId) as HTMLIFrameElement;
  if (!iframe) {
    window.open('https://www.canva.com/create/', '_blank');
    return;
  }

  try {
    const canvas = await html2canvas(iframe.contentDocument!.body, {
      useCORS: true,
      scale: 2 // High resolution for Canva
    });
    
    const blob = await new Promise<Blob | null>(res => canvas.toBlob(res, 'image/png'));
    if (!blob) throw new Error("Capture failed");

    const fileName = `canva_${Date.now()}_${Math.random().toString(36).substring(7)}.png`;
    const { error: uploadError } = await supabase.storage
      .from('manifests')
      .upload(fileName, blob);

    if (uploadError) throw uploadError;

    const { data: { publicUrl } } = supabase.storage
      .from('manifests')
      .getPublicUrl(fileName);

    // Canva Media Import URL
    window.open(`https://www.canva.com/create/design?media=${encodeURIComponent(publicUrl)}`, '_blank');
  } catch (err) {
    console.error("[KREO] Canva automation failed:", err);
    window.open('https://www.canva.com/create/', '_blank');
  }
};
