import JSZip from 'jszip';
import html2canvas from 'html2canvas';
import pptxgen from 'pptxgenjs';

export const exportAsHTML = (code: string) => {
  const blob = new Blob([code], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "kreo-manifestation.html";
  document.body.appendChild(a); // Required for some browsers
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const exportAsZip = async (code: string) => {
  const zip = new JSZip();
  zip.file("index.html", code);
  zip.file("README.md", `# KREO Manifestation\n\nThis artifact was generated by KREO.\n\n## Setup\nSimply open \`index.html\` in any modern browser to view the manifest.`);
  
  const content = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(content);
  const a = document.createElement("a");
  a.href = url;
  a.download = "kreo-dev-package.zip";
  a.click();
  URL.revokeObjectURL(url);
};

export const exportAsPPTX = async (iframeId: string) => {
  const iframe = document.getElementById(iframeId) as HTMLIFrameElement;
  if (!iframe) return;

  const canvas = await html2canvas(iframe.contentDocument!.body);
  const imgData = canvas.toDataURL('image/png');

  const pptx = new pptxgen();
  const slide = pptx.addSlide();
  slide.addImage({ data: imgData, x: 0, y: 0, w: '100%', h: '100%' });
  
  pptx.writeFile({ fileName: "kreo-presentation.pptx" });
};

export const exportToCanva = () => {
  window.open('https://www.canva.com/create/', '_blank');
};
